name: Jest_API & Playwright_UI test

on:
  workflow_dispatch:
  push:
    branches:
  pull_request:
    branches: [ "master" ]

permissions:
  checks: write
  contents: write
  pages: write
  id-token: write
  deployments: write

jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      # Step 1: API Tests
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Update dependencies
        run: npm update
      - name: Run Jest api_tests
        id: api_tests
        run: npm run test:api
        continue-on-error: true

      # Step 2: API Tests Artifact
      - name: Upload api_tests artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: jest-report
          if-no-files-found: error
          path: ./reports/jest/
          retention-days: 30

      # Step 3: UI Tests
      - name: Install Browsers for Playwright ui_tests
        run: npx playwright install --with-deps
      - name: Run Playwright ui_tests
        id: ui_tests
        run: npm run test:ui:ci
        continue-on-error: true

      # Step 4: UI Tests Artifact
      - name: Upload ui_tests artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          if-no-files-found: error
          path: ./reports/playwright/
          retention-days: 30

      # Step 5: Check Errors
      - name: Check Errors
        run: echo "::set-output name=api_tests_status::${{ steps.api_tests.outcome }}"
        continue-on-error: true

      # Step 6: Deploy and Telegram Message
      - name: Deploy united artifacts on github-pages
        needs: [api_tests, ui_tests]
        uses: JamesIves/github-pages-deploy-action@v4
        continue-on-error: true
        with:
          folder: reports
          clean: true
          token: ${{ secrets.TOKEN }}

      - name: Send telegram message on push
        needs: [api_tests, ui_tests]
        uses: appleboy/telegram-action@master
        with:
          to: -${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            Click the link to view the changes.: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            
            You will be able to access the latest testing reports in five minutes using the provided link: https://pavdem2012.github.io/graduationProject/
